repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe, --allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: clear-notebooks-output
        name: clear-notebooks-output
        files: tools/.*\.ipynb$
        stages: [pre-commit]
        language: python
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        additional_dependencies: [jupyter]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - -l
          - "120"
          - --force-single-line-imports
          - --profile
          - black
