[project]
name = "anemoi-plugins-meteoswiss"
version = "0.1.0"
description = "Anemoi plugins used at MeteoSwiss"
readme = "README.md"
authors = [{ name = "MeteoSwiss" }]
requires-python = ">=3.11"
dependencies = [
    "anemoi-datasets",
    "anemoi-plugins",
    "anemoi-transform",
    "earthkit-meteo",
    "meteodata-lab",
]


[project.scripts]
anemoi-plugins-meteoswiss = "anemoi_plugins_meteoswiss:main"

[project.entry-points."anemoi.transform.filters"]
average-flux-to-cumulative-quantity = "anemoi_plugins_meteoswiss.transform.filters:AverageFluxToCumulativeQuantity"
destagger = "anemoi_plugins_meteoswiss.transform.filters:Destagger"
clip-lateral-boundaries = "anemoi_plugins_meteoswiss.transform.filters:ClipLateralBoundaries"
model-to-pressure-level = "anemoi_plugins_meteoswiss.transform.filters:ModelToPressureLevel"
assign-grid = "anemoi_plugins_meteoswiss.transform.filters:AssignGrid"
gaussian-smoother = "anemoi_plugins_meteoswiss.transform.filters:GaussianSmoother"
icon-remap-to-reg-lat-lon = "anemoi_plugins_meteoswiss.transform.filters:IconRemapToRegLatLon"
omega-from-w = "anemoi_plugins_meteoswiss.transform.filters:OmegaFromW"
geopotential-from-height = "anemoi_plugins_meteoswiss.transform.filters:GeopotentialFromHeight"

[project.entry-points."anemoi.datasets.create.sources"]
rea-l-ch1-precip = "anemoi_plugins_meteoswiss.transform.sources:ReaLCh1Precip"
rea-l-ch1-wind-gust = "anemoi_plugins_meteoswiss.transform.sources:ReaLCh1WindGust"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
]

[tool.uv.sources]
anemoi-plugins = { git = "https://github.com/ecmwf/anemoi-plugins.git" }
earthkit-meteo = { git = "https://github.com/ecmwf/earthkit-meteo.git" , rev = "develop" }
meteodata-lab = { git = "https://github.com/MeteoSwiss/meteodata-lab.git", rev = "main" }
